# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='0XX-XXX-XXXX', max_length=13),
        ),
    ]
