# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20170915_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
