# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_class_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='male', max_length=20),
            preserve_default=False,
        ),
    ]
