# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
