# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_auto_20170926_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bank_account',
        ),
    ]
