# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_merge_20170926_1119'),
        ('membership', '0016_remove_customer_bank_account'),
    ]

    operations = [
    ]
