# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0021_auto_20171027_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default='unknown'),
        ),
    ]
