# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_remove_customer_bank_account'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_no', models.CharField(max_length=13)),
                ('ccv', models.CharField(max_length=3)),
                ('owner', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Customer')),
            ],
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
