# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20170928_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expire_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
