# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20170930_1943'),
        ('payment', '0005_auto_20170930_1813'),
    ]

    operations = [
    ]
