# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_merge_20171002_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
