# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170908_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='materials',
        ),
        migrations.AddField(
            model_name='material',
            name='patterns',
            field=models.ManyToManyField(to='catalog.Pattern'),
        ),
    ]
