# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='file_name',
        ),
    ]
