# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_pattern_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='description',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
