# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_design_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Design')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Material')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='material_id',
        ),
        migrations.AddField(
            model_name='pattern',
            name='material_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.Material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
            preserve_default=False,
        ),
    ]
