# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170928_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='pattern',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='design_id',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='material',
            name='patterns',
        ),
    ]
