# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='design',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
