# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170928_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Design')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Material')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
            preserve_default=False,
        ),
    ]
