# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20170928_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='image_name',
            field=models.CharField(default='default.txt', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.Design'),
        ),
    ]
