# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20171003_2003'),
        ('catalog', '0012_auto_20171003_1924'),
    ]

    operations = [
    ]
