# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20171004_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalog.Design'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalog.Material'),
        ),
    ]
