# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20171004_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
        migrations.AddField(
            model_name='design',
            name='yard',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
