# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20171003_2151'),
        ('catalog', '0015_auto_20171004_1843'),
    ]

    operations = [
    ]
