# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20171022_0100'),
        ('catalog', '0016_merge_20171004_2253'),
    ]

    operations = [
    ]
