# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20171022_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
