# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_merge_20171022_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='price',
        ),
    ]
