# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_design_price'),
        ('catalog', '0018_promotion_description'),
    ]

    operations = [
    ]
