# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_promotion_products'),
        ('catalog', '0020_merge_20171023_1539'),
    ]

    operations = [
    ]
