# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_class_discount'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='membership.Customer'),
            preserve_default=False,
        ),
    ]
