# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20170930_1813'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='payment.CreditCard'),
            preserve_default=False,
        ),
    ]
