# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_transportation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='credit',
            new_name='creditcard',
        ),
    ]
