# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20171004_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='remarks',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
