# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_orderinfo_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='remarks',
            field=models.TextField(default=0, max_length=100),
        ),
    ]
