# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20171022_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='final_price',
        ),
    ]
