# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_address'),
        ('cart', '0007_auto_20171023_1456'),
    ]

    operations = [
    ]
