# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_merge_20171104_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_product',
            field=models.IntegerField(),
        ),
    ]
