# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_merge_20171023_1549'),
        ('cart', '0009_auto_20171104_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='associate_promotion',
            field=models.ManyToManyField(to='catalog.Promotion'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='remarks',
            field=models.TextField(default='', max_length=100),
        ),
    ]
