# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20171109_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
