# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20171109_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=150),
        ),
    ]
